// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDocUserMerch = "doc_user_merchs"

// DocUserMerch mapped from table <doc_user_merchs>
type DocUserMerch struct {
	ID      *string `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	RootID  string  `gorm:"column:root_id;type:uuid;not null" json:"root_id"`
	MerchID string  `gorm:"column:merch_id;type:uuid;not null" json:"merch_id"`
}

// TableName DocUserMerch's table name
func (*DocUserMerch) TableName() string {
	return TableNameDocUserMerch
}
