// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDocUser = "doc_users"

// DocUser mapped from table <doc_users>
type DocUser struct {
	ID        *string    `gorm:"column:id;type:text;primaryKey" json:"id"`
	UserID    string     `gorm:"column:user_id;type:text;not null" json:"user_id"`
	Name      string     `gorm:"column:name;type:text;not null" json:"name"`
	Balance   int32      `gorm:"column:balance;type:integer;not null" json:"balance"`
	CreatedAt time.Time `gorm:"column:created_at;autoCreateTime" json:"created_at"`
}

// TableName DocUser's table name
func (*DocUser) TableName() string {
	return TableNameDocUser
}
