// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDocUserMerch = "doc_user_merchs"

// DocUserMerch mapped from table <doc_user_merchs>
type DocUserMerch struct {
	ID        *string `gorm:"column:id;type:text;primaryKey" json:"id"`
	RootID    string  `gorm:"column:root_id;type:text;not null" json:"root_id"`
	MerchCode string  `gorm:"column:merch_code;type:code;not null" json:"merch_code"`
}

// TableName DocUserMerch's table name
func (*DocUserMerch) TableName() string {
	return TableNameDocUserMerch
}
