// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDocMerchTransaction = "doc_merch_transactions"

// DocMerchTransaction mapped from table <doc_merch_transactions>
type DocMerchTransaction struct {
	ID         *string    `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	MerchCode  string     `gorm:"column:merch_code;type:uuid;not null" json:"merch_code"`
	ReceiverID string     `gorm:"column:receiver_id;type:uuid;not null" json:"receiver_id"`
	Amount     int32      `gorm:"column:amount;type:integer;not null" json:"amount"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp without time zone;index:idx_doc_merch_transactions_created_at,priority:1;default:now()" json:"created_at"`
}

// TableName DocMerchTransaction's table name
func (*DocMerchTransaction) TableName() string {
	return TableNameDocMerchTransaction
}
