// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInfoUser = "info_users"

// InfoUser mapped from table <info_users>
type InfoUser struct {
	ID        *string    `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	UserID    string     `gorm:"column:user_id;type:uuid;not null" json:"user_id"`
	Name      string     `gorm:"column:name;type:text;not null" json:"name"`
	Balance   int32      `gorm:"column:balance;type:integer;not null" json:"balance"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp without time zone;index:idx_info_users_created_at,priority:1;default:now()" json:"created_at"`
}

// TableName InfoUser's table name
func (*InfoUser) TableName() string {
	return TableNameInfoUser
}
