version: '3.8'

services:
  avito-shop-service:
    build: ./golang
    container_name: avito-shop-service
    ports:
      - "8080:8080"
    env_file:
      - ./envs/local.env
    networks:
      - internal

  avito-shop-postgres:
    image: postgres:13
    container_name: avito-shop-postgres
    env_file:
      - ./envs/local.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
    - internal

networks:
  internal:
