// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInfoUser = "info_users"

// InfoUser mapped from table <info_users>
type InfoUser struct {
	ID        *string    `gorm:"column:id;type:text;primaryKey;default:gen_random_uuid()" json:"id"`
	Name      *string    `gorm:"column:name;type:text" json:"name"`
	Email     string     `gorm:"column:email;type:text;not null" json:"email"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp without time zone" json:"updated_at"`
}

// TableName InfoUser's table name
func (*InfoUser) TableName() string {
	return TableNameInfoUser
}
